# Fly.io Configuration for Exam Evaluator Frontend
app = "exam-evaluator-frontend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.fly"

# Network configuration - prefer IPv4
[experimental]
  private_network = true

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 400

[[http_service.checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/"

[env]
  NODE_ENV = "production"

# Machine specifications
[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
