services:
  # Database
  postgres:
    image: postgres:16.2-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - exam-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Cache
  redis:
    image: redis:7.2.4-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/cache:/var/lib/redis/data
    ports:
      - "127.0.0.1:${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - exam-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Message Queue
  rabbitmq:
    image: rabbitmq:3.13.0-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "127.0.0.1:${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "127.0.0.1:15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - exam-network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Database Admin
  pgadmin:
    image: dpage/pgadmin4:8.5
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - "${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - exam-network

  # Celery Monitor
  flower:
    build:
      context: ./backend/libs/flower/
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5555:5555"
    volumes:
      - ./backend/libs/compose/flower:/app
    depends_on:
      - rabbitmq
    env_file:
      - .env
    networks:
      - exam-network

  # Content/Exam Evaluation Service
  content-service:
    build:
      context: ./backend
      dockerfile: content_service/compose/local/Dockerfile
    volumes:
      - ./backend/content_service:/app/content_service
      - ./backend/libs:/app/libs
      - ./backend/requirements.txt:/app/requirements.txt
      - ./backend/uploads:/app/uploads
      - uv-cache:/root/.cache/uv
    ports:
      - "0.0.0.0:8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - exam-network

  # Content Worker (Celery)
  content-worker:
    build:
      context: ./backend
      dockerfile: content_service/compose/local/DockerfileWorker
    volumes:
      - ./backend/content_service:/app/content_service
      - ./backend/libs:/app/libs
      - ./backend/requirements.txt:/app/requirements.txt
      - uv-cache:/root/.cache/uv
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - exam-network

  # Content Beat (Celery Scheduler)
  content-beat:
    build:
      context: ./backend
      dockerfile: content_service/compose/local/DockerfileBeat
    volumes:
      - ./backend/content_service:/app/content_service
      - ./backend/libs:/app/libs
      - ./backend/requirements.txt:/app/requirements.txt
      - uv-cache:/root/.cache/uv
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - exam-network

  # Authentication Service
  auth-service:
    build:
      context: ./backend
      dockerfile: auth_service/compose/local/Dockerfile
    volumes:
      - ./backend/auth_service:/app/auth_service
      - ./backend/libs:/app/libs
      - ./backend/requirements.txt:/app/requirements.txt
      - uv-cache:/root/.cache/uv
    ports:
      - "0.0.0.0:8004:8004"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - exam-network

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8004/api/v1
    depends_on:
      - auth-service
      - content-service
    networks:
      - exam-network

networks:
  exam-network:

volumes:
  uv-cache:
    # Shared volume for uv package manager cache to speed up builds
    # This volume is mounted at /root/.cache/uv in all services
