# Fly.io configuration for Auth Service
app = "exam-evaluator-auth"
primary_region = "iad"

[build]
  dockerfile = "fly/auth-service/Dockerfile"

[env]
  PORT = "8004"
  PYTHONUNBUFFERED = "1"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8004
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

# Health check geçici olarak disabled - endpoint eklenene kadar
# [[http_service.checks]]
#   interval = "15s"
#   timeout = "10s"
#   grace_period = "30s"
#   method = "GET"
#   path = "/"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2
