# Fly.io configuration for Content Service
app = "exam-evaluator-content"
primary_region = "iad"

[build]
  dockerfile = "fly/content-service/Dockerfile"

[env]
  PORT = "8001"
  PYTHONUNBUFFERED = "1"
  PYTHONPATH = "/app"

[mounts]
  source = "content_uploads"
  destination = "/app/uploads"
  initial_size = "10gb"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2
