# Fly.io configuration for Redis
app = "exam-evaluator-redis"
primary_region = "iad"

[build]
  image = "redis:7.2.4-alpine"

[mounts]
  source = "redis_data"
  destination = "/data"
  initial_size = "3gb"

[processes]
  app = "redis-server --requirepass cache"

[[services]]
  internal_port = 6379
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 6379

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 2
