# Fly.io configuration for Auth Service
app = "exam-evaluator-auth"
primary_region = "iad"

[build]
  dockerfile = "fly/auth-service/Dockerfile"

[env]
  PORT = "8004"
  PYTHONUNBUFFERED = "1"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8004
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2
