# Fly.io Configuration for Exam Evaluator Backend
app = "exam-evaluator-backend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.fly"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

[[http_service.checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/health"

[env]
  ENV_NAME = "PRODUCTION"
  DEBUG = "false"
  POSTGRES_PORT = "5432"
  REDIS_PORT = "6379"
  RABBITMQ_PORT = "5672"

# Machine specifications
[vm]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

# Persistent storage for uploads
[mounts]
  source = "exam_uploads"
  destination = "/app/uploads"
