"""Add exam_title to evaluations

Revision ID: 4a5b6c7d8e9f
Revises: d1779f677718
Create Date: 2025-10-19 14:30:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4a5b6c7d8e9f"
down_revision = "d1779f677718"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("evaluations", sa.Column("exam_title", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evaluations", "exam_title")
    # ### end Alembic commands ###
