"""

Revision ID: e7566f5b6a0b
Revises: ef0e11383788
Create Date: 2025-10-17 20:15:57.622872

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e7566f5b6a0b"
down_revision = "ef0e11383788"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluations",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("evaluation_id", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PARSING", "EVALUATING", "COMPLETED", "FAILED", name="evaluationstatus"),
            nullable=False,
        ),
        sa.Column("progress_percentage", sa.Float(), nullable=True),
        sa.Column("current_message", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("answer_key_filename", sa.String(length=255), nullable=False),
        sa.Column("answer_key_path", sa.String(length=500), nullable=False),
        sa.Column("answer_key_data", sa.JSON(), nullable=True),
        sa.Column("total_students", sa.Integer(), nullable=True),
        sa.Column("completed_students", sa.Integer(), nullable=True),
        sa.Column("average_score", sa.Float(), nullable=True),
        sa.Column("max_possible_score", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evaluations_evaluation_id"), "evaluations", ["evaluation_id"], unique=True)
    op.create_index(op.f("ix_evaluations_status"), "evaluations", ["status"], unique=False)
    op.create_index(op.f("ix_evaluations_user_id"), "evaluations", ["user_id"], unique=False)
    op.create_table(
        "student_responses",
        sa.Column("evaluation_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.String(length=100), nullable=False),
        sa.Column("student_name", sa.String(length=255), nullable=True),
        sa.Column("pdf_filename", sa.String(length=255), nullable=False),
        sa.Column("pdf_path", sa.String(length=500), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=True),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.Column("percentage", sa.Float(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("topic_gaps", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_student_responses_evaluation_id"), "student_responses", ["evaluation_id"], unique=False)
    op.create_index(op.f("ix_student_responses_student_id"), "student_responses", ["student_id"], unique=False)
    op.create_table(
        "followup_questions",
        sa.Column("evaluation_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("student_response_id", sa.Integer(), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_response_id"],
            ["student_responses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_followup_questions_evaluation_id"), "followup_questions", ["evaluation_id"], unique=False)
    op.create_index(
        op.f("ix_followup_questions_student_response_id"), "followup_questions", ["student_response_id"], unique=False
    )
    op.create_index(op.f("ix_followup_questions_user_id"), "followup_questions", ["user_id"], unique=False)
    op.create_table(
        "question_responses",
        sa.Column("student_response_id", sa.Integer(), nullable=False),
        sa.Column("question_number", sa.Integer(), nullable=False),
        sa.Column("student_answer", sa.Text(), nullable=False),
        sa.Column("expected_answer", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=False),
        sa.Column("additional_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["student_response_id"],
            ["student_responses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_responses_student_response_id"), "question_responses", ["student_response_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_question_responses_student_response_id"), table_name="question_responses")
    op.drop_table("question_responses")
    op.drop_index(op.f("ix_followup_questions_user_id"), table_name="followup_questions")
    op.drop_index(op.f("ix_followup_questions_student_response_id"), table_name="followup_questions")
    op.drop_index(op.f("ix_followup_questions_evaluation_id"), table_name="followup_questions")
    op.drop_table("followup_questions")
    op.drop_index(op.f("ix_student_responses_student_id"), table_name="student_responses")
    op.drop_index(op.f("ix_student_responses_evaluation_id"), table_name="student_responses")
    op.drop_table("student_responses")
    op.drop_index(op.f("ix_evaluations_user_id"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_status"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_evaluation_id"), table_name="evaluations")
    op.drop_table("evaluations")
    # ### end Alembic commands ###
