"""

Revision ID: d1779f677718
Revises: e7566f5b6a0b
Create Date: 2025-10-18 16:41:41.689580

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d1779f677718"
down_revision = "e7566f5b6a0b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("student_responses", sa.Column("strengths", sa.JSON(), nullable=True))
    op.add_column("student_responses", sa.Column("weaknesses", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("student_responses", "weaknesses")
    op.drop_column("student_responses", "strengths")
    # ### end Alembic commands ###
