"""

Revision ID: da8992e73a68
Revises: 07dbd4e2c956
Create Date: 2025-04-12 12:27:18.060287

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da8992e73a68"
down_revision = "07dbd4e2c956"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "blogs", "title", existing_type=sa.VARCHAR(length=200), type_=sa.String(length=9999), existing_nullable=False
    )
    op.alter_column(
        "blogs", "summary", existing_type=sa.VARCHAR(length=500), type_=sa.String(length=9999), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "blogs", "summary", existing_type=sa.String(length=9999), type_=sa.VARCHAR(length=500), existing_nullable=True
    )
    op.alter_column(
        "blogs", "title", existing_type=sa.String(length=9999), type_=sa.VARCHAR(length=200), existing_nullable=False
    )
    # ### end Alembic commands ###
