"""

Revision ID: 60caf5a9add9
Revises: 02e5e40e7f03
Create Date: 2025-04-07 17:12:52.125884

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "60caf5a9add9"
down_revision = "02e5e40e7f03"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("daily_trackers", sa.Column("bowel_movement", sa.String(length=50), nullable=True))
    op.add_column("daily_trackers", sa.Column("urine_color", sa.String(length=50), nullable=True))
    op.add_column("daily_trackers", sa.Column("menstrual_phase", sa.String(length=50), nullable=True))
    op.add_column("daily_trackers", sa.Column("training_quality", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("daily_trackers", "training_quality")
    op.drop_column("daily_trackers", "menstrual_phase")
    op.drop_column("daily_trackers", "urine_color")
    op.drop_column("daily_trackers", "bowel_movement")
    # ### end Alembic commands ###
