"""

Revision ID: 8fe110461048
Revises: 58d7650b53b9
Create Date: 2025-04-07 13:02:39.732321

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8fe110461048"
down_revision = "58d7650b53b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_trackers",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("energy", sa.Integer(), nullable=True),
        sa.Column("sleep", sa.Integer(), nullable=True),
        sa.Column("stress", sa.Integer(), nullable=True),
        sa.Column("muscle_soreness", sa.Integer(), nullable=True),
        sa.Column("fatigue", sa.Integer(), nullable=True),
        sa.Column("hunger", sa.Integer(), nullable=True),
        sa.Column("water_intake_liters", sa.Float(), nullable=True),
        sa.Column("sleep_hours", sa.Float(), nullable=True),
        sa.Column("mood", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_daily_trackers_user_id"), "daily_trackers", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_daily_trackers_user_id"), table_name="daily_trackers")
    op.drop_table("daily_trackers")
    # ### end Alembic commands ###
