"""

Revision ID: 239e8b8797f9
Revises: 6b3b37f7b608
Create Date: 2025-04-16 20:09:11.894659

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "239e8b8797f9"
down_revision = "6b3b37f7b608"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("body_trackers", sa.Column("rate", sa.Float(), nullable=True))
    op.add_column("daily_trackers", sa.Column("rate", sa.Float(), nullable=True))
    op.add_column("fasting_meal_logs", sa.Column("rate", sa.Float(), nullable=True))
    op.add_column("fasting_workout_logs", sa.Column("rate", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fasting_workout_logs", "rate")
    op.drop_column("fasting_meal_logs", "rate")
    op.drop_column("daily_trackers", "rate")
    op.drop_column("body_trackers", "rate")
    # ### end Alembic commands ###
# Refactored on 2025-07-18: Improved code structure
# Updated on 2025-07-19: Improved code documentation
# Fixed formatting on 2025-07-19
# Updated on 2025-07-19: Improved code documentation
