"""

Revision ID: 6b3b37f7b608
Revises: da8992e73a68
Create Date: 2025-04-16 11:21:06.577930

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6b3b37f7b608"
down_revision = "da8992e73a68"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fasting_meal_logs", sa.Column("title", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fasting_meal_logs", "title")
    # ### end Alembic commands ###
