"""

Revision ID: 4f39466f5e59
Revises: ff18bbe5ff34
Create Date: 2025-04-09 13:36:35.009230

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4f39466f5e59"
down_revision = "ff18bbe5ff34"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "blog_tags",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "blogs",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=True),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=True),
        sa.Column("blog_type", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["blog_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_blogs_user_id"), "blogs", ["user_id"], unique=False)
    op.create_table(
        "blog_tag_association",
        sa.Column("blog_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["blog_id"],
            ["blogs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["blog_tags.id"],
        ),
        sa.PrimaryKeyConstraint("blog_id", "tag_id"),
    )
    op.create_table(
        "fasting_meal_logs",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("photo_url", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("protein", sa.Float(), nullable=True),
        sa.Column("carbs", sa.Float(), nullable=True),
        sa.Column("fat", sa.Float(), nullable=True),
        sa.Column("detailed_macros", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["fasting_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fasting_meal_logs_session_id"), "fasting_meal_logs", ["session_id"], unique=False)
    op.create_index(op.f("ix_fasting_meal_logs_user_id"), "fasting_meal_logs", ["user_id"], unique=False)
    op.create_table(
        "fasting_workout_logs",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("workout_name", sa.String(length=100), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("calories_burned", sa.Integer(), nullable=True),
        sa.Column("intensity", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["fasting_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fasting_workout_logs_session_id"), "fasting_workout_logs", ["session_id"], unique=False)
    op.create_index(op.f("ix_fasting_workout_logs_user_id"), "fasting_workout_logs", ["user_id"], unique=False)
    op.add_column("fasting_plans", sa.Column("target_week", sa.Integer(), nullable=True))
    op.add_column("fasting_plans", sa.Column("target_protein", sa.Float(), nullable=True))
    op.add_column("fasting_plans", sa.Column("target_carb", sa.Float(), nullable=True))
    op.add_column("fasting_plans", sa.Column("target_fat", sa.Float(), nullable=True))
    op.add_column("fasting_sessions", sa.Column("mood", sa.String(length=50), nullable=True))
    op.add_column("fasting_sessions", sa.Column("stage", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fasting_sessions", "stage")
    op.drop_column("fasting_sessions", "mood")
    op.drop_column("fasting_plans", "target_fat")
    op.drop_column("fasting_plans", "target_carb")
    op.drop_column("fasting_plans", "target_protein")
    op.drop_column("fasting_plans", "target_week")
    op.drop_index(op.f("ix_fasting_workout_logs_user_id"), table_name="fasting_workout_logs")
    op.drop_index(op.f("ix_fasting_workout_logs_session_id"), table_name="fasting_workout_logs")
    op.drop_table("fasting_workout_logs")
    op.drop_index(op.f("ix_fasting_meal_logs_user_id"), table_name="fasting_meal_logs")
    op.drop_index(op.f("ix_fasting_meal_logs_session_id"), table_name="fasting_meal_logs")
    op.drop_table("fasting_meal_logs")
    op.drop_table("blog_tag_association")
    op.drop_index(op.f("ix_blogs_user_id"), table_name="blogs")
    op.drop_table("blogs")
    op.drop_table("blog_tags")
    op.drop_table("blog_categories")
    # ### end Alembic commands ###
