"""

Revision ID: 02e5e40e7f03
Revises: 8fe110461048
Create Date: 2025-04-07 14:11:55.806658

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "02e5e40e7f03"
down_revision = "8fe110461048"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workout_trackers",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("calories_burned", sa.Integer(), nullable=True),
        sa.Column("sets", sa.Integer(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("custom_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workout_trackers_user_id"), "workout_trackers", ["user_id"], unique=False)
    op.create_index(op.f("ix_workout_trackers_workout_id"), "workout_trackers", ["workout_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workout_trackers_workout_id"), table_name="workout_trackers")
    op.drop_index(op.f("ix_workout_trackers_user_id"), table_name="workout_trackers")
    op.drop_table("workout_trackers")
    # ### end Alembic commands ###
