"""

Revision ID: 07dbd4e2c956
Revises: 5f557aac1417
Create Date: 2025-04-12 11:50:22.079909

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07dbd4e2c956"
down_revision = "5f557aac1417"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blogs", sa.Column("language", sa.String(length=10), nullable=True))
    op.add_column("fasting_workout_logs", sa.Column("ai_content", sa.String(length=9999), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fasting_workout_logs", "ai_content")
    op.drop_column("blogs", "language")
    # ### end Alembic commands ###
