name: Auto Commit

on:
  schedule:
    # Run once daily at midnight UTC
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update timestamp file
        run: |
          # Create or update timestamp file
          echo "Last updated: $(date)" > last_updated.txt

          # Add some random data to ensure the commit is unique
          echo "Random: $RANDOM" >> last_updated.txt

          # Debug information
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la

      - name: Commit and push if changed
        run: |
          git config --global user.name 'AliYmn'
          git config --global user.email 'aliymn.db@gmail.com'

          git add last_updated.txt

          # Only commit and push if there are changes
          git diff --staged --quiet || (git commit -m "Auto update: $(date)" && git push)
