name: Auto Commit

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/1 * * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Use a personal access token to allow pushing to the repository
          token: ${{ secrets.AUTO_COMMIT_TOKEN }}

      - name: Setup Git user
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Update timestamp file
        run: |
          # Create or update timestamp file
          echo "Last updated: $(date)" > last_updated.txt

          # Add some random data to ensure the commit is unique
          echo "Random: $RANDOM" >> last_updated.txt

      - name: Commit and push changes
        run: |
          # Check if there are changes to commit
          if git diff --exit-code; then
            echo "No changes to commit"
            exit 0
          fi

          git add last_updated.txt
          git commit -m "Auto update: $(date)"
          git push
