name: Auto Commit

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/1 * * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Use the default GitHub token
          token: ${{ github.token }}

      - name: Setup Git user
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Update timestamp file
        run: |
          # Create or update timestamp file
          echo "Last updated: $(date)" > last_updated.txt

          # Add some random data to ensure the commit is unique
          echo "Random: $RANDOM" >> last_updated.txt

      - name: Commit and push changes
        run: |
          # Add the file first
          git add last_updated.txt

          # Check if there are changes to commit
          if git diff --staged --exit-code; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Auto update: $(date)"
          git push
